# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "sbi_rs"
authors = ["Rivos, Inc."]
license = "Apache-2.0"
version = "0.2.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
static_assertions = "1.1"
flagset = "0.4.3"

[lib]
path = "./src/sbi.rs"
